branches:
  except:
    - master

version: "{build} ~ {branch}"

os: Visual Studio 2017

environment:
  matrix:
    - CHANNEL: stable
      ARCH: x86_64
      ABI: msvc
      TARGET: x86_64-pc-windows-msvc

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init.exe -yv --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV

artifacts:
  - path: target\%TARGET%\debug\wasmer.exe
    name: wasmer.exe

build_script:
  - cargo build --verbose

test_script:
  - set RUST_BACKTRACE=1
  - cargo test --verbose
