[package]
name = "wasmer"
version = "0.1.3"
authors = ["Syrus Akbary <me@syrusakbary.com>"]
edition = "2018"
repository = "https://github.com/wasmerio/wasmer"
publish = true
description = "High-Performance WebAssembly JIT interpreter"
license = "MIT"
build = "build/mod.rs"
include = [
    "examples/**/*",
    "src/**/*",
    "Cargo.lock",
    "Cargo.toml",
    "LICENSE",
    "Makefile",
    "/README.md",
    "rustfmt.toml"
]

[dependencies]
cranelift-native = "0.26.0"
# cranelift-native = { path = "cranelift/lib/native" }
cranelift-codegen = "0.26.0"
# cranelift-codegen = { path = "cranelift/lib/codegen" }
cranelift-entity = "0.26.0"
# cranelift-entity = { path = "cranelift/lib/entity" }
cranelift-wasm = "0.26.0"
# cranelift-wasm = { path = "cranelift/lib/wasm" }
docopt = "1.0.0"
serde = "1.0.55"
serde_derive = "1.0.55"
tempdir = "0.3.7"
error-chain = "0.12.0"
errno = "0.2.4"
structopt = "0.2.11"
wabt = "0.7.2"
wasmparser = "0.20.0"
winapi = "0.3.6"
region = "0.3.0"
# spin = "0.4.10"
log = "0.4.5"
target-lexicon = "0.2.0"
# libc = "0.2"
libc = { git = "https://github.com/rust-lang/libc" }
nix = "0.12.0"
rayon = "1.0.3"
byteorder = "1"
indicatif = "0.10"
console = "0.7.1"

[build-dependencies]
wabt = "0.7.2"
# [dev-dependencies]
# libffi = "0.6.4"
# maplit = "1.0.1"

[features]
default = ["fast-tests"]

debug = []
# This feature will allow cargo test to run much faster
fast-tests = []
