[target.'cfg(target_os = "linux")']
rustflags = [
    # Put the VM functions in the dynamic symbol table.
    "-C", "link-arg=-Wl,-E",
    # Fix the SONAME, required by CMake, see https://github.com/wasmerio/wasmer/issues/2429.
    "-C", "link-arg=-Wl,-soname,libwasmer.so",
]
