on:
  push:
    branches:
      - '**'
      - '!master'

name: wasmerjs

env:
  RUST_BACKTRACE: 1

jobs:
  wasmerjs:
    name: Wasmer-JS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
      - name: Install WasmPack
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Test Wasmer-JS
        run: make test-js
